### ISSUE TITLE
Does not run on ARM64. `exec format error`

### ISSUE THREAD

**Issue by Qwertie-** [e-m-b-a/emba#472]
**Describe the bug**
Attempted to run on the ARM build of Kali Linux (In a VM running on an M1 Macbook)

**To Reproduce**
1. EMBA installation (default mode)
3. run `sudo docker-compose run emba`

**Expected behavior**
Expected to not crash. 

Terminal output:
```

┌──(user㉿kali)-[~/emba]
└─$ sudo docker-compose run emba                                                              
WARNING: The FIRMWARE variable is not set. Defaulting to a blank string.
WARNING: The LOG variable is not set. Defaulting to a blank string.
WARNING: The EMBA variable is not set. Defaulting to a blank string.
Creating emba_emba_run ... done
exec /bin/bash: exec format error
ERROR: 1
```

**Desktop (please complete the following information):**
- OS: Kali Linux 2022.04 (Apple Silicon ARM64 iso)
- EMBA version: Not too sure, can't run to print version. Installed today via the git clone + docker install method
- Installation method: default with up to date docker image

**Comment by m-1-k-3** [comment]
Hi @Qwertie-,

Thank you for your report. EMBA is not designed to run on ARM architecture. If you can run a VM with a x64 Image you should switch. I will include this limitation to the wiki.

Best,
Mike

**Comment by m-1-k-3** [comment]
Included now into the wiki: https://github.com/e-m-b-a/emba/wiki/Installation#prerequisites

Will close this issue now

**Comment by floyd-fuh** [comment]
Soo... this is a 2023 issue. But by now it's 2026, a lot of people know how fast and power-efficient ARM is, the Mac-World (and quite a good part of security researchers use Mac too) is heavily focused on ARM. Other laptops are starting to ship with ARM too.

I switched from my Intel Mac to an M4 last year, but that simply means I won't be able to run EMBA at all.

Unfortunately, there is still no good way to run x64 VMs on Mac, the Parallels implementation is the best and is absolutely horribly unusable. The only option is to run Ubuntu ARM64 with Rosetta.

What is the reason for not supporting ARM? Which parts would need porting?

**Comment by m-1-k-3** [comment]
Hi @floyd-fuh,

I totally would love to see EMBA on ARM. In theory this should not be the biggest deal as a lot of components are available via apt/pip or a simple build process. I think the devil will be in the detail and there will be a lot of pitfalls that we need to find and solve somehow. As the current installer needs a bigger refactoring (see also [here](https://github.com/e-m-b-a/emba/issues/1849)) we should consider this also during such a process. Unfortunately, we do not have the need and the resources to move into this direction. Nevertheless, if you are willing to start including support of ARM in EMBA we are happy to support you.

**Comment by floyd-fuh** [comment]
I'm using Ubuntu 24.04 ARM64 with Rosetta (default Parallels click and install). Rosetta is the translation layer of Apple to run amd64 on ARM64.

The EMBA installer only failed because `docker pull` by default tries to pull the host architecture and there is no ARM64 image for EMBA, but with `docker pull embeddedanalyzer/emba:2.0.1a --platform linux/amd64` before running the installer it works.

Anything outside the docker container that prevents usage of ARM64 for EMBA? So far (progress 57/74, 10 hours in) it looks like it runs just fine... So I think you can change the documentation:

* ARM64 machines are only supported as long as the docker container can run as an amd64 container. This was tested on MacOS with Parallels and Parallel's current "Ubuntu 24.04 (with Rosetta)" one-click-install VM that uses Apple's "Rosetta dynamic binary translator" to run amd64 binaries and docker containers. Before running the EMBA installer, reconfigure the VM to use 24GB RAM, 10 cpu cores and 200GB of disc space (make sure you resize the disc partition in the VM to use the free space, e.g. with `gparted`). Also make sure you pull the amd64 docker container with `docker pull embeddedanalyzer/emba:2.0.1a --platform linux/amd64`, then run the installer in classic mode (with docker, `sudo ./installer.sh -d`) and ignore the warnings about unsupported architecture and missing SSSE3 support. Please remember the RAM and CPU requirements, they apply as usually with EMBA.

@m-1-k-3 Let me know if there is anything you have in mind I should test to make sure that everything works fine, but I did not encounter any issues apart from a couple of warnings that the architecture is not supported.

**Comment by m-1-k-3** [comment]
looks quite cool to me. As long as you get the docker base image up and runnning everything should work as expected. We could use this post as a entry in our wiki. So, we do not loose the information on how to setup EMBA on a Mac. What do you think?

**Comment by floyd-fuh** [comment]
Sure, feel free to either copy the text to the documentation somewhere or just point here

**Comment by m-1-k-3** [comment]
Thank you very much ... 
https://github.com/e-m-b-a/emba/wiki/EMBA-on-ARM64-based-MacOS
https://github.com/e-m-b-a/emba/wiki/Installation#prerequisites

**Comment by floyd-fuh** [comment]
Looks like the scan finished... kind of. It stalled. There was only one module running at the end, which never finished. Except for the status file (showing high CPU usage), there were no new files written to the emba-log folder for 24h. So I quit and the results look fine.

**Comment by m-1-k-3** [comment]
Could you share the firmware? So, I can do a check in my environment. Probably we have something to fix

**Comment by floyd-fuh** [comment]
Unfortunately I can't

**Comment by m-1-k-3** [comment]
If you find the issue let us know
